# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3  # Use latest stable Ruff version
    hooks:
      - id: ruff-check
        args: [--fix]
        # Optional: only run on these folders
        # files: ^(src)/
        # exclude: ^(src/legacy|.*test_data)

      - id: ruff-format 
