services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.0
    container_name: weaviate
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"

      ENABLE_MODULES: "backup-s3,backup-filesystem"
      BACKUP_S3_ENABLED: "true"
      BACKUP_FILESYSTEM_ENABLED: "true"

      # ✅ Set the local backup path
      BACKUP_FILESYSTEM_PATH: "/backups"

      # Optional for cluster migration
      CLUSTER_HOSTNAME: "node1"

      # S3 config
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_WEAVIATE}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_WEAVIATE}
      AWS_REGION: ${AWS_REGION}

      BACKUP_S3_BUCKET: ${S3_BUCKET_NAME_WEAVIATE_BACKUP}
      BACKUP_S3_ENDPOINT: ${S3_WEAVIATE_BACKUP_ENDPOINT}
      BACKUP_S3_USE_SSL: "true"

    volumes:
      - ./weaviate/weaviate_data:/var/lib/weaviate
      - ./weaviate/weaviate_backups:/backups        # 👈 Host path mapped to container path
    networks:
      - weaviate_network



networks:
  weaviate_network:
    driver: bridge
